spring:
  application:
    name: JobSwipe
  datasource:
    url: jdbc:postgresql://db.ewaacqxaozyuloyqzcou.supabase.co:5432/postgres
    username: postgres
    password: TIEhn2qmUtofssG
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
              batch_size: '10'
            order_inserts: 'true'
  flyway:
    enabled: false

server:
  port: 4196

security:
  jwt:
    secret-key: i7QwDugB3oSCG4gOtiRmq42bK3UrCkB6uqVBRTUTVfQ=
    expiration-time: 3600000

google:
  api-key: "XNqNDXqXXj7rjesXOBWSRki+NbrLcIzq7AIco1UHx3I="
  cx: "f2aad16898c394f74"

search:
  sites:
    - boards.greenhouse.io
    - job-boards.greenhouse.io

#  roles:
#    software engineer:
#      - software engineer
#      - software developer
#      - sde
#    backend engineer:
#      - backend engineer
#      - backend
#    frontend engineer:
#      - frontend engineer
#      - frontend
#    fullstack engineer:
#      - fullstack engineer
#      - fullstack

  locations:
    india:
      - India
    bengaluru:
      - Bengaluru
      - Bangalore
    mumbai:
      - Mumbai
    chennai:
      - Chennai
    pune:
      - Pune
    hyderabad:
      - Hyderabad
    noida:
      - Noida
    gurgaon:
      - Gurgaon
    delhi:
      - Delhi
    remote india:
      - Remote India

  catchalls:
    - engineer India
    - India software

scheduling:
  seedAggregatorServiceCron: "0 */5 * * * *"